import React from 'react'
import logo from "../../../../Assets/logo.png"

        const eighteen = [
            {src: {logo},
            name: "Random1",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random2",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random3",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random4",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random5",
            desig: "junior Executive",
            },
            {src: {logo},
            name: "Random6",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random7",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random8",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random9",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random10",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random11",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random12",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random13",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random14",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random15",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random16",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random17",
            desig: "junior Executive",
            }, 
        ]

export default eighteen;