import logo from "../../../../Assets/logo.png"

        const nineteen = [
            {src: {logo},
            name: "Randoma",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Randomb",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Randomc",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Randomd",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Randome",
            desig: "junior Executive",
            },
            {src: {logo},
            name: "Randomf",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Randomg",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Randomh",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Randomi",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Randomj",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Randomk",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Randoml",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Randomm",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Randomn",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Randomo",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Randomp",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Randomq",
            desig: "junior Executive",
            }, 
        ]

export default nineteen;