
import logo from "../../../../Assets/Gandhi Jayanti.png"

// const twentyOne = () => {
//     return (
        const twentyTwo = [
            {src: {logo},
            name: "Arshad Ahmed",
            desig: "Senior Executive",
            }, 
            {src: {logo},
            name: "Afsana Yasmin",
            desig: "Senior Executive",
            }, 
            {src: {logo},
            name: "Manash Pratim Goswami",
            desig: "Senior Executive",
            }, 
            {src: {logo},
            name: "Nihar Basisth",
            desig: "Senior Executive",
            }, 
            {src: {logo},
            name: "Dhritiraj Borah",
            desig: "Senior Executive",
            },
            {src: {logo},
            name: "Prapti Kashyap",
            desig: "Senior Executive",
            }, 
            {src: {logo},
            name: "Debanga Bikash Bora",
            desig: "Senior Executive",
            }, 
            {src: {logo},
            name: "Nayan Deka",
            desig: "Senior Executive",
            }, 
            {src: {logo},
            name: "Rupah Anand Hazarika",
            desig: "Senior Executive",
            }, 
            {src: {logo},
            name: "Satyik Pritam Yogi",
            desig: "Senior Executive",
            }, 
            {src: {logo},
            name: "Emon Kalita",
            desig: "Senior Executive",
            }, 
            {src: {logo},
            name: "Sai Lahari J",
            desig: "Senior Executive",
            }, 
            {src: {logo},
            name: "Diksha Kakati",
            desig: "Senior Executive",
            }, 
            {src: {logo},
            name: "Himanta Biswa Deka",
            desig: "Senior Executive",
            }, 
            {src: {logo},
            name: "Karuna Rabha",
            desig: "Senior Executive",
            }, 
            {src: {logo},
            name: "Rajanya Kashyap Gogoi",
            desig: "Senior Executive",
            }, 
            {src: {logo},
            name: "Nishad Tasnim",
            desig: "Senior Executive",
            }, 
        ]
//     )
// }
export default twentyTwo;