import React from 'react'
import logo from "../../../../Assets/logo.png"

        const twentyOne = [
            {src: {logo},
            name: "Random",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random",
            desig: "junior Executive",
            },
            {src: {logo},
            name: "Random",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random",
            desig: "junior Executive",
            }, 
            {src: {logo},
            name: "Random",
            desig: "junior Executive",
            }, 
        ]

export default twentyOne